### ISSUE TITLE
UWP - _adapter.DisconnectDeviceAsync() doesn't work - plugin ver. 2.2.0-pre2

### ISSUE THREAD

**Issue by Auto72** [dotnet-bluetooth-le/dotnet-bluetooth-le#423]
## Steps to reproduce

1. UWP application project with BLE Plugin version: 2.2.0-pre2

2. Open a connection with a device 

await _adapter.ConnectToDeviceAsync(_device);
_myService = await _device.GetServiceAsync(wantedServicetUUID);
_myCharacteristic = await __myService GetCharacteristicAsync(wantedCharacteristicUUID));

_myCharacteristic.ValueUpdated += (o, args) =>
{
    var bytes = args.Characteristic.Value;
};
await _myCharacteristic .StartUpdatesAsync();

3. Close the Connection

await _myCharacteristic.StopUpdatesAsync();
await _adapter.DisconnectDeviceAsync(_device);

## Expected behavior
The connection with the bluetooth LE device is closed.

## Actual behavior
The connection with the bluetooth LE device is NOT closed.
The following command, never ends:

await _adapter.DisconnectDeviceAsync(_device);

### Crashlog

No crash occurs.

## Configuration

Version of the Plugin: 2.2.0-pre2

Platform: Windows 10 1909

Device: Windows 10 1909

**Comment by smsissuechecker** [comment]
Hi @Auto72,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by JongChern** [comment]
Hi was wondering if there are any immediate plans to get this fix released on nuget

**Comment by sisaacks** [comment]
Hello has this been added to Pre2?  I am still seeing this issue

**Comment by TStein1984** [comment]
@JanNepras @xabre @janusw @sisaacks if have the same issue. Is there some hack to fix it or another solution so solve the problem for UWP? Thanks in advance.

**Comment by janusw** [comment]
Does this still occur with 3.0.0-beta.2?

**Comment by Auto72** [comment]
Still doesn't work with 3.0.0-beta.2.

IDevice device;
ICharacteristic fifoCharacteristic;

The following command now crashes in UWP, even if it is surrounded by a try catch block:

await adapter.DisconnectDeviceAsync(device);

Sometimes also the following command crashes on UWP  (called before the previous one):

await fifoCharacteristic.StopUpdatesAsync();

**Comment by janusw** [comment]
Fixed via #721 in [3.0.0-beta.5](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/releases/tag/3.0.0-beta.5).
